- hosts: all
  vars_files:
    - password.yml      
  gather_facts: False
  tasks:
    - name: Save the ESXi configuration On FTP
      vmware_cfg_backup:
       hostname: '{{ ansible_host }}'
       username: root
       password: '{{ password }}'
       validate_certs: no
       state: saved
       dest: #pathtosave#
    - name: upload file
      shell: |
        lftp #ftpserver# -u #ftpuser#,#ftppassword#<<EOF
        cd /Infra/esxi_config
        mirror -R #SourcePath# #DestPath#
        bye
        EOF
      register: result
